NOM: othernames
PRENOM: firstname
#CIVILITE: title
NOM_USAGE: surname
ADRESSE_ANNEE: address
ADRESSE_ANNEE2: address2
VILLE_ANNEE: city
CP_ANNEE: zipcode
EMAIL_ANNEE: email
TEL_ANNEE: phone
MOBILE_ANNEE: mobile
EMAIL_PERSO: emailpro
ADRESSE_FIXE: B_address
VILLE_FIXE: B_city
CP_FIXE: B_zipcode
TEL_FIXE: B_phone
DATE_NAISS: dateofbirth
CATEGORYCODE: categorycode
COMPOSANTE: [branchcode,COMPOSANTE,POLETHEM]
STATUT: STATUT
#FILIERE
CODE_ETAPE: CODEETAPE
NUM_INE: INE
NUM_APPLI_GEST: [APPLIGEST]
IDENT_LDAP: userid
--- 
categorycode:
        1: L
        3: D
        2: M
        4: L
        5: M
        6: L
        7: M
#        NON ENSEIGNANT: PRO
#        ENSEIGNANT: P
#        CHERCHEUR: P
        L0: L
        0: L
        A: L
branchcode:
    AOS: U1BULA
    CFM: U1BULA
    CH: U1BULA
    GEO: U1BULA
    LAC: U1BULA
    LAG: U1BULA
    MSH: U1BULA
    PSY: U1BULA
    UNI: U1BULA
    AFC: U1BULA
    MI1: U1BULA
    CH2: U1BULA
    IU1: U1BULA
    ARL: U1BULA
    IAR: U1BULA
    ARC: U1BULA
    IMG: U1BULA
    MAC: U1BULA
    SAT: U1BULA
    IU4: U1IUFMAVI
    IDI: U1BUSC
    IU3: U1IUFMDI
    SCE: U1BULA
    IU2: U1IUFMMA
    CFC: U1BUSC
    ETS: U1BUSC
    SM:  U1BUSC
    ICF: U1BUSC
    SVT: U1BUSC
    GDM: U1BUSC
    IUT: U1BUSC
    AM1: U1BUSC
    SRI: U1BUSC
    DEN: U1BUSC
    AC1: U1BUSC
    LG1: U1BUSC
    CH1: U1BUSC
    GE1: U1BUSC
    AO1: U1BUSC
    MI2: U1BUSC
    MI3: U1BUSC
    SM2: U1BUSC
    EP1: U1BUSC
    IUF: U1IUFMMA
    GBM: U1BUSC
    SV1: U1BUSC
    MIM: U1BUCG
    STI: U1BUCG
    GSI: U1BUCG
    EPU: U1BUCG
    SM1: U1BUCG
    IU5: U1BUCG
    MI4: U1BUCG
    PLU: U1BULA
    LPS: U1BULA
    L12: U1BULA
    MED: U2TIMONMED
    PHA: U2PHARMA
    ODO: U2TIMONMED
    SEC: U2AIXECO
    ECM: U2MRSECO
    ECG: U2GAP
    STM: U2LUMINY
    STG: U2GAP
    SCE: U2LUMINY
    ESI: U2LUMINY
    OSU: U2LUMINY
    IM2: U2LUMINY
    IUT: IUT 
    IUT: IUT
    IUG: U2GAP
    IUL: U2IUTSHE
    IUM: U2LUMINY
    JOU: U2PHARMA
    40: U3BUSSJ
    41: U3BUSSJ
    C0: U3BAISPEC
    D0: U3BUDAIX
    D1: U3BUCAN
    D2: U3BAARL
    D3: U3BUMTP
    E0: U3BUDAIX
    E1: U3BUCAN
    E2: U3BAARL
    E6: U3BUDAIX
    F0: U3BUIEFEE
    G0: U3BUIEFEE
    G1: U3BUCAN
    M0: U3BUDAIX
    P0: U3BAIEP
    R0: U3BUDAIX
    S1: U3BUSSJ
    S2: U3BUMTP
    S3: U3BAARL
    S4: U3BUSSJ
    T0: U3BUIAE
POLETHEM:
    AOS: Lettres
    CFC: Sciences
    CFM: Lettres
    CH: Lettres
    ETS: Sciences
    GBM: Sciences
    GEO: Lettres
    IMG: Sciences
    LAC: Lettres
    LAG: Lettres
    MIM: Sciences
    MSH: Lettres
    PSY: Lettres
    SCE: Lettres
    SM: Sciences
    STI: Sciences
    UNI: Lettres
    ICF: Sciences
    SVT: Sciences
    AFC: Lettres
    ARL: Lettres
    GSI: Sciences
    GDM: Sciences
    EPU: Sciences
    IUT: Sciences
    IAR: Sciences
    IDI: Sciences
    MAC: Lettres
    AM1: Sciences
    ARC: Lettres
    SRI: Sciences
    DEN: Sciences
    SAT: Sciences
    AC1: Lettres
    PLU: Lettres
    MI1: Sciences
    LPS: Lettres
    L12: Lettres
    LG1: Lettres
    CH1: Lettres
    GE1: Lettres
    AO1: Lettres
    CH2: Lettres
    MI2: Sciences
    MI3: Sciences
    MI4: Sciences
    SM1: Sciences
    SM2: Sciences
    SV1: Sciences
    EP1: Sciences
    IUF: Lettres
    IU1: Lettres
    IU2: Lettres
    IU3: Lettres
    IU4: Lettres
    IU5: Lettres
    MED: Santé
    PHA: Santé
    ODO: Santé
    SEC: Economie
    ECM: Economie
    ECG: Economie
    STM: Sciences
    STG: Sciences
    SCE: Sciences
    ESI: Sciences
    OSU: Sciences
    IM2: Sciences
    IUT: IUT
    IUT: IUT
    IUG: Economie
    IUL: Sciences
    IUM: Sciences
    JOU: Economie
    40: Sciences
    41: Sciences
    C0: Droit
    D0: Droit
    D1: Droit
    D2: Droit
    D3: Droit
    E0: Economie
    E1: Economie
    E2: Economie
    E6: Economie
    F0: Lettres
    G0: Economie
    G1: Economie
    M0: Lettres
    P0: Droit
    R0: Droit
    S1: Sciences
    S2: Sciences
    S3: Sciences
    S4: Sciences
    T0: Economie
COMPOSANTE:
    AOS: U1AOS
    CFC: U1CFC
    CFM: U1CFMI
    CH: U1CIV
    ETS: U1IUPEN
    GBM: U1GBM
    GEO: U1GEO
    IMG: U1IMG
    LAC: U1LACS
    LAG: U1LAG
    MIM: U1MIM
    MSH: U1MSH
    PSY: U1PSY
    SCE: U1SCE
    SM: U1SM
    STI: U1STI
    UNI: U1SRIA
    ICF: U1ICF
    SVT: U1SVT
    AFC: U1AFC
    ARL: U1LACSAR
    GSI: U1GSI
    GDM: U1GDM
    EPU: U1EPU
    IUT: U1IUTM
    IAR: U1IUTAR
    IDI: U1IUTDI
    MAC: U1MAC
    AM1: U1
    ARC: U1CIVAR
    SRI: U1SRIM
    DEN: U1DEN
    SAT: U1SAT
    AC1: U1LACM
    PLU: U1PLU
    MI1: U1MIMA
    LPS: U1LPS
    L12: U1L12
    LG1: U1LAGM
    CH1: U1CIVM
    GE1: U1GEOM
    AO1: U1AOSM
    CH2: U1CIVJ
    MI2: U1MIMSC
    MI3: U1MIMSJ
    MI4: U1MIMSA
    SM1: U1SMCG
    SM2: U1SVTSC
    SV1: U1SVTLU
    EP1: U1EPUSJ
    IUF: U1IUFM
    IU1: U1IUFMA
    IU2: U1IUFMM
    IU3: U1IUFMDI
    IU4: U1IUFMAVI
    IU5: U1IUFMCG
    MED: U2MED
    PHA: U2PHA
    ODO: U2ODO
    SEC: U2SEC
    ECM: U2ECM
    ECG: U2ECG
    STM: U2STM
    STG: U2STG
    SCE: U2SCE
    ESI: U2ESI
    OSU: U2OSU
    IM2: U2IM2
    IUT: U2IUT
    IUG: U2IUG
    IUL: U2IUL
    IUM: U2IUM
    JOU: U2JOU
    40:  U3IUTMRS
    C0:  U3ISPEC
    D0:  U3FDSPAIX
    D1:  U3FDSPMRS
    D2:  U3FDSPARL
    D3:  U3FDSPMTP
    E0:  U3FEAAIX
    E1:  U3FEAMRS
    E2:  U3FEAARL
    E6:  U3FEAFORB
    F0:  U3IEFEE
    G0:  U3IMPGTAIX
    G1:  U3IMPGTMRS
    M0:  U3MFC
    P0:  U3IEP
    R0:  U3IAR
    S1:  U3FSTMRS
    S2:  U3FSTAIX
    S3:  U3FSTARL
    S4:  U3FSTDIG
    T0:  U3IAE
--- 
  - firstname,surname,dateofbirth
--- |
$$fromdata{'ETABLISSEM'}='U3';

--- |
my %ce2su3e = (
	'3718' => 'D',
	'D805' => 'D',
	'D807' => 'D',
	'D808' => 'D',
	'E7250' => 'D',
	'E7260' => 'D',
	'E8AA' => 'D',
	'E8AB' => 'D',
	'E8AC' => 'D',
	'E8BA' => 'D',
	'E8CA' => 'D',
	'G800' => 'D',
	'P71' => 'D',
	'P8CA' => 'D',
	'P8DA' => 'D',
	'P8EA' => 'D',
	'P8FA' => 'D',
	'R70' => 'D',
	'S800' => 'D',
	'S801' => 'D',
	'S802' => 'D',
	'S803' => 'D',
	'S804' => 'D',
	'S805' => 'D',
	'S806' => 'D',
	'S807' => 'D',
	'S808' => 'D',
	'S809' => 'D',
	'S810' => 'D',
	'S811' => 'D',
	'S812' => 'D',
	'S813' => 'D',
	'S816' => 'D',
	'S8AA' => 'D',
	'S8AB' => 'D',
	'S8AC' => 'D',
	'S8BB' => 'D',
	'S8BD' => 'D',
	'S8BE' => 'D',
	'S8CA' => 'D',
	'S8DA' => 'D',
	'S8DB' => 'D',
	'S8EA' => 'D',
	'S8ED' => 'D',
	'S8EE' => 'D',
	'S8FA' => 'D',
	'S8FB' => 'D',
	'S8GA' => 'D',
	'S8GB' => 'D',
	'T701' => 'D',
	'U7TEST' => 'D',
	'D810' => 'D',
	'E801' => 'D',
	'P80' => 'D',
	'S815' => 'D',
	'T80' => 'D',
	'D01A' => 'L1',
	'D01M' => 'L1',
	'D02A' => 'L1',
	'M40E' => 'L1',
	'M40G' => 'L1',
	'M41G' => 'L1',
	'S0A0' => 'L1',
	'S0B0' => 'L1',
	'22U11' => 'L1',
	'41701' => 'L1',
	'B13' => 'L1',
	'B1U1' => 'L1',
	'D1ABA' => 'L1',
	'D1ABM' => 'L1',
	'D1T0A9' => 'L1',
	'D1T0B9' => 'L1',
	'D1T0F9' => 'L1',
	'D1T0J9' => 'L1',
	'D1T0M9' => 'L1',
	'D1T0N9' => 'L1',
	'D1T0R9' => 'L1',
	'D1U7' => 'L1',
	'E1L0A' => 'L1',
	'E1L0AC' => 'L1',
	'E1L0M' => 'L1',
	'E1Q0A' => 'L1',
	'E1Q0AC' => 'L1',
	'E1V0A' => 'L1',
	'E1V0AC' => 'L1',
	'E1V0M' => 'L1',
	'E1V0MC' => 'L1',
	'F10' => 'L1',
	'F20' => 'L1',
	'F30' => 'L1',
	'F40' => 'L1',
	'F50' => 'L1',
	'G1B0' => 'L1',
	'N1A0' => 'L1',
	'N1B0' => 'L1',
	'N1C0' => 'L1',
	'N1C2A' => 'L1',
	'N1D0' => 'L1',
	'N1E0' => 'L1',
	'N1E0A' => 'L1',
	'N1F0' => 'L1',
	'N1F00' => 'L1',
	'N1G0' => 'L1',
	'N1H0' => 'L1',
	'P1U00' => 'L1',
	'P1U16' => 'L1',
	'P1UEP' => 'L1',
	'S0U1' => 'L1',
	'S1G0A' => 'L1',
	'S1G0AC' => 'L1',
	'S1G0M' => 'L1',
	'S1M0A' => 'L1',
	'S1M0AC' => 'L1',
	'S1M0M' => 'L1',
	'S1M0MC' => 'L1',
	'S1P0A' => 'L1',
	'S1P0AC' => 'L1',
	'S1P0M' => 'L1',
	'S1P0MC' => 'L1',
	'S1T0A' => 'L1',
	'S1V0A' => 'L1',
	'S1V0AC' => 'L1',
	'S1V0M' => 'L1',
	'S1V0MC' => 'L1',
	'22U12' => 'L2',
	'41702' => 'L2',
	'B23' => 'L2',
	'B2U1' => 'L2',
	'C10' => 'L2',
	'D2ABM' => 'L2',
	'D2T0A9' => 'L2',
	'D2T0B9' => 'L2',
	'D2T0F9' => 'L2',
	'D2T0J9' => 'L2',
	'D2T0M9' => 'L2',
	'D2T0R9' => 'L2',
	'D2U4' => 'L2',
	'E2L0A' => 'L2',
	'E2L0M' => 'L2',
	'E2Q0A' => 'L2',
	'E2Q0AC' => 'L2',
	'E2UEP' => 'L2',
	'E2V0A' => 'L2',
	'E2V0AC' => 'L2',
	'E2V0M' => 'L2',
	'E2V0MC' => 'L2',
	'F109' => 'L2',
	'F112' => 'L2',
	'G2B0' => 'L2',
	'G2U1' => 'L2',
	'N2A1' => 'L2',
	'N2A1V' => 'L2',
	'N2B1' => 'L2',
	'N2B1P' => 'L2',
	'N2C1' => 'L2',
	'N2C2' => 'L2',
	'N2C2A' => 'L2',
	'N2D1' => 'L2',
	'N2D2' => 'L2',
	'N2E1' => 'L2',
	'N2E2' => 'L2',
	'N2E2A' => 'L2',
	'N2E2C' => 'L2',
	'N2E3' => 'L2',
	'N2F1' => 'L2',
	'N2F1C' => 'L2',
	'N2F2' => 'L2',
	'N2G1' => 'L2',
	'N2H1' => 'L2',
	'N2H1P' => 'L2',
	'P2U00' => 'L2',
	'P2U16' => 'L2',
	'P2U17' => 'L2',
	'S2G0A' => 'L2',
	'S2G0M' => 'L2',
	'S2G0MC' => 'L2',
	'S2M0A' => 'L2',
	'S2M0AC' => 'L2',
	'S2M0M' => 'L2',
	'S2P0A' => 'L2',
	'S2P0AC' => 'L2',
	'S2P0M' => 'L2',
	'S2T0A' => 'L2',
	'S2V0A' => 'L2',
	'S2V0M' => 'L2',
	'B33' => 'L3',
	'B3U1' => 'L3',
	'C20' => 'L3',
	'D3ABA' => 'L3',
	'D3ABM' => 'L3',
	'D3B0A9' => 'L3',
	'D3B0B9' => 'L3',
	'D3B0F9' => 'L3',
	'D3B0M9' => 'L3',
	'D3B0N9' => 'L3',
	'D3B0R9' => 'L3',
	'D3C0A' => 'L3',
	'D3D08' => 'L3',
	'D3U13' => 'L3',
	'D3U3' => 'L3',
	'D3U5' => 'L3',
	'D3U6' => 'L3',
	'D3U61' => 'L3',
	'E3L1A' => 'L3',
	'E3L1M' => 'L3',
	'E3M1A' => 'L3',
	'E3M1G' => 'L3',
	'E3M2A' => 'L3',
	'E3M2M' => 'L3',
	'E3N1A' => 'L3',
	'E3N2A' => 'L3',
	'E3N3A' => 'L3',
	'E3N4R' => 'L3',
	'E3P1A' => 'L3',
	'E3Q1A' => 'L3',
	'E3U2' => 'L3',
	'E3U7' => 'L3',
	'E3U9' => 'L3',
	'G3B1A' => 'L3',
	'G3B1M' => 'L3',
	'G3B2A' => 'L3',
	'G3B2M' => 'L3',
	'N3U1' => 'L3',
	'N3U10' => 'L3',
	'N3U2' => 'L3',
	'N3U9' => 'L3',
	'P3C0' => 'L3',
	'P3U00' => 'L3',
	'P3U16' => 'L3',
	'P3U17' => 'L3',
	'P3U4' => 'L3',
	'P92' => 'L3',
	'P941' => 'L3',
	'P942' => 'L3',
	'S3G1M' => 'L3',
	'S3G2M' => 'L3',
	'S3M1M' => 'L3',
	'S3M2M' => 'L3',
	'S3P1M' => 'L3',
	'S3P2M' => 'L3',
	'S3P3M' => 'L3',
	'S3P6M' => 'L3',
	'S3S0M' => 'L3',
	'S3T3A' => 'L3',
	'S3UEP' => 'L3',
	'S3V1M' => 'L3',
	'S3V2M' => 'L3',
	'T3U11' => 'L3',
	'C30' => 'L3',
	'C30S' => 'L3',
	'P93' => 'L3',
	'P93EL' => 'L3',
	'D3AB' => 'L3',
	'D3BA' => 'L3',
	'E3GA' => 'L3',
	'E3GAV' => 'L3',
	'E3HA' => 'L3',
	'E3JA' => 'L3',
	'N3BA' => 'L3',
	'N3BAC' => 'L3',
	'N3BAP' => 'L3',
	'N3BB' => 'L3',
	'N3BBC' => 'L3',
	'N3BBP' => 'L3',
	'N3CA' => 'L3',
	'N3CAC' => 'L3',
	'N3CAP' => 'L3',
	'N3CB' => 'L3',
	'N3CBA' => 'L3',
	'N3CBC' => 'L3',
	'N3DAC' => 'L3',
	'N3DB' => 'L3',
	'N3DBC' => 'L3',
	'N3DBP' => 'L3',
	'N3DBV' => 'L3',
	'N3EAA' => 'L3',
	'N3EAP' => 'L3',
	'N3EB' => 'L3',
	'N3EBC' => 'L3',
	'N3EBP' => 'L3',
	'N3EC' => 'L3',
	'N3FA' => 'L3',
	'N3FAC' => 'L3',
	'N3FAP' => 'L3',
	'N3FAV' => 'L3',
	'N3FB' => 'L3',
	'N3FBC' => 'L3',
	'N3FBP' => 'L3',
	'N3FBV' => 'L3',
	'N3FC' => 'L3',
	'N3FCC' => 'L3',
	'N3FCP' => 'L3',
	'N3FCV' => 'L3',
	'N3FD' => 'L3',
	'N3FDC' => 'L3',
	'N3GA' => 'L3',
	'N3GAA' => 'L3',
	'N3GB' => 'L3',
	'N3GBC' => 'L3',
	'N3GC' => 'L3',
	'S3AA' => 'L3',
	'S3AB' => 'L3',
	'S3AC' => 'L3',
	'S3AD' => 'L3',
	'S3AE' => 'L3',
	'S3BC' => 'L3',
	'S3CA' => 'L3',
	'S3DA' => 'L3',
	'S3EA' => 'L3',
	'B41' => 'M1',
	'D4AF' => 'M1',
	'D4AFD' => 'M1',
	'D4AFE' => 'M1',
	'D4AFF' => 'M1',
	'D4AFG' => 'M1',
	'D4HS' => 'M1',
	'D4NT' => 'M1',
	'D4NTE' => 'M1',
	'D4PA' => 'M1',
	'D4PAE' => 'M1',
	'D4PL' => 'M1',
	'D4PLD' => 'M1',
	'D4PLE' => 'M1',
	'D4PLG' => 'M1',
	'D4PLJ' => 'M1',
	'D4PR' => 'M1',
	'D4PRE' => 'M1',
	'D4SA' => 'M1',
	'D4SC' => 'M1',
	'D4U14' => 'M1',
	'D4U2' => 'M1',
	'D4U3' => 'M1',
	'D4U66' => 'M1',
	'D4U9' => 'M1',
	'D4UEP' => 'M1',
	'D5U21' => 'M1',
	'E4J0' => 'M1',
	'E4L0' => 'M1',
	'E4L0G' => 'M1',
	'E4MA' => 'M1',
	'E4PAA' => 'M1',
	'E4PAM' => 'M1',
	'E4PAP' => 'M1',
	'E4RA' => 'M1',
	'E4U6' => 'M1',
	'E5U15' => 'M1',
	'G4DA' => 'M1',
	'G4DB' => 'M1',
	'G4DC' => 'M1',
	'G4DE' => 'M1',
	'G4DF' => 'M1',
	'G4DG' => 'M1',
	'G4DH' => 'M1',
	'P4GC' => 'M1',
	'P4GK' => 'M1',
	'P4U10' => 'M1',
	'P4U11' => 'M1',
	'P4U12' => 'M1',
	'P4U13' => 'M1',
	'P4U14' => 'M1',
	'P4U15' => 'M1',
	'P4U16' => 'M1',
	'R4CA' => 'M1',
	'R4DA' => 'M1',
	'S4AG0' => 'M1',
	'S4CH1' => 'M1',
	'S4CH2' => 'M1',
	'S4CH3' => 'M1',
	'S4CHA' => 'M1',
	'S4CSA' => 'M1',
	'S4ET1' => 'M1',
	'S4ET2' => 'M1',
	'S4ETA' => 'M1',
	'S4ETB' => 'M1',
	'S4GP0' => 'M1',
	'S4MN0' => 'M1',
	'S4MT0' => 'M1',
	'S4NS0' => 'M1',
	'S4NT0' => 'M1',
	'S4PH0' => 'M1',
	'S4QL0' => 'M1',
	'S4YSA' => 'M1',
	'S4YSB' => 'M1',
	'S4YSC' => 'M1',
	'T4D0' => 'M1',
	'T4D0E' => 'M1',
	'T4D0M' => 'M1',
	'R5CA' => 'M2',
	'R5DA' => 'M2',
	'R5DB' => 'M2',
	'R5DC' => 'M2',
	'2903' => 'M2',
	'A5U10' => 'M2',
	'A5U2' => 'M2',
	'A5U9' => 'M2',
	'B51' => 'M2',
	'D5AFA' => 'M2',
	'D5AFB' => 'M2',
	'D5AFC' => 'M2',
	'D5AFCN' => 'M2',
	'D5AFD' => 'M2',
	'D5AFE' => 'M2',
	'D5AFEN' => 'M2',
	'D5AFF' => 'M2',
	'D5AFFN' => 'M2',
	'D5AFG' => 'M2',
	'D5AFH' => 'M2',
	'D5AFJ' => 'M2',
	'D5AFK' => 'M2',
	'D5AFKN' => 'M2',
	'D5AFL' => 'M2',
	'D5AFM' => 'M2',
	'D5HSA' => 'M2',
	'D5HSAN' => 'M2',
	'D5NTA' => 'M2',
	'D5NTB' => 'M2',
	'D5NTC' => 'M2',
	'D5NTD' => 'M2',
	'D5NTG' => 'M2',
	'D5NTH' => 'M2',
	'D5NTJ' => 'M2',
	'D5PAA' => 'M2',
	'D5PAB' => 'M2',
	'D5PAC' => 'M2',
	'D5PAD' => 'M2',
	'D5PAF' => 'M2',
	'D5PAG' => 'M2',
	'D5PAH' => 'M2',
	'D5PLA' => 'M2',
	'D5PLB' => 'M2',
	'D5PLC' => 'M2',
	'D5PLD' => 'M2',
	'D5PLE' => 'M2',
	'D5PRB' => 'M2',
	'D5PRC' => 'M2',
	'D5PRD' => 'M2',
	'D5PRE' => 'M2',
	'D5PRG' => 'M2',
	'D5PRH' => 'M2',
	'D5PRHN' => 'M2',
	'D5SAA' => 'M2',
	'D5SAAN' => 'M2',
	'D5SCA' => 'M2',
	'D5SCB' => 'M2',
	'D5SCC' => 'M2',
	'D5SCD' => 'M2',
	'D5U14' => 'M2',
	'D5U2' => 'M2',
	'D5U20' => 'M2',
	'D5U20H' => 'M2',
	'D5U3' => 'M2',
	'D5U47M' => 'M2',
	'D5U50' => 'M2',
	'D5U56' => 'M2',
	'D5U63' => 'M2',
	'D5U64' => 'M2',
	'D5U65' => 'M2',
	'D5UA1' => 'M2',
	'D5UA2' => 'M2',
	'D5UA3' => 'M2',
	'D5UEP' => 'M2',
	'D801' => 'M2',
	'D801M' => 'M2',
	'E5JA' => 'M2',
	'E5JB' => 'M2',
	'E5JC' => 'M2',
	'E5JF' => 'M2',
	'E5L3' => 'M2',
	'E5LBG' => 'M2',
	'E5LC' => 'M2',
	'E5LD' => 'M2',
	'E5LE' => 'M2',
	'E5LF' => 'M2',
	'E5MA' => 'M2',
	'E5PAM' => 'M2',
	'E5PAP' => 'M2',
	'E5RA' => 'M2',
	'E5U3' => 'M2',
	'E5U6' => 'M2',
	'E5UEP' => 'M2',
	'G5DA' => 'M2',
	'G5DB' => 'M2',
	'G5DC' => 'M2',
	'G5DD' => 'M2',
	'G5DE' => 'M2',
	'G5DF' => 'M2',
	'G5DG' => 'M2',
	'G5UEP' => 'M2',
	'J03' => 'M2',
	'P5G4' => 'M2',
	'P5GA' => 'M2',
	'P5GB' => 'M2',
	'P5GC' => 'M2',
	'P5GD' => 'M2',
	'P5GE' => 'M2',
	'P5GF' => 'M2',
	'P5GG' => 'M2',
	'P5GH' => 'M2',
	'P5GK' => 'M2',
	'P5U1' => 'M2',
	'P5U10' => 'M2',
	'P5U11' => 'M2',
	'P5U12' => 'M2',
	'P5U13' => 'M2',
	'P5U14' => 'M2',
	'P5U15' => 'M2',
	'P5UEP' => 'M2',
	'P91' => 'M2',
	'R5UEP' => 'M2',
	'S5AG0' => 'M2',
	'S5CHA' => 'M2',
	'S5CSA' => 'M2',
	'S5ETA' => 'M2',
	'S5ETB' => 'M2',
	'S5GPA' => 'M2',
	'S5MNA' => 'M2',
	'S5MTA' => 'M2',
	'S5NTA' => 'M2',
	'S5QLA' => 'M2',
	'S5QLB' => 'M2',
	'S5UEP' => 'M2',
	'S5YSAA' => 'M2',
	'S5YSAB' => 'M2',
	'S5YSBA' => 'M2',
	'S5YSBB' => 'M2',
	'S5YSC' => 'M2',
	'T5CA' => 'M2',
	'T5CA1' => 'M2',
	'T5CA2' => 'M2',
	'T5CAC' => 'M2',
	'T5CAE' => 'M2',
	'T5CAN' => 'M2',
	'T5CAP' => 'M2',
	'T5DB' => 'M2',
	'T5DC' => 'M2',
	'T5DD' => 'M2',
	'T5DE' => 'M2',
	'T5DF' => 'M2',
	'T5DG' => 'M2',
	'T5DH' => 'M2',
	'T5DHM' => 'M2',
	'T5DJ' => 'M2',
	'T5U11' => 'M2',
	'T5U15' => 'M2',
	'T5U16' => 'M2',
	'T5U3' => 'M2',
	'T5U72' => 'M2',
	'T5UEP' => 'M2',
	'D5AF1' => 'M2',
	'D5AF2' => 'M2',
	'D5AF3' => 'M2',
	'D5AN1' => 'M2',
	'D5HS1' => 'M2',
	'D5NT1' => 'M2',
	'D5NT2' => 'M2',
	'D5NT3' => 'M2',
	'D5NT4' => 'M2',
	'D5NT5' => 'M2',
	'D5NT6' => 'M2',
	'D5PA1' => 'M2',
	'D5PA3' => 'M2',
	'D5PL1' => 'M2',
	'D5PL2' => 'M2',
	'D5PL3' => 'M2',
	'D5PL4' => 'M2',
	'D5PL5' => 'M2',
	'D5PL6' => 'M2',
	'D5PR1' => 'M2',
	'D5PR2' => 'M2',
	'D5PR3' => 'M2',
	'D5PR4' => 'M2',
	'D5PR5' => 'M2',
	'D5PRA' => 'M2',
	'D5SA1' => 'M2',
	'D5SA1N' => 'M2',
	'D5SC1' => 'M2',
	'E5JD' => 'M2',
	'E5JE' => 'M2',
	'E5L1' => 'M2',
	'E5L2' => 'M2',
	'E5M1' => 'M2',
	'G5E1' => 'M2',
	'P5G1' => 'M2',
	'P5G2' => 'M2',
	'P5G3' => 'M2',
	'P5G6' => 'M2',
	'S5CH2' => 'M2',
	'S5CH3' => 'M2',
	'S5ET1' => 'M2',
	'S5ET2' => 'M2',
	'S5GP1' => 'M2',
	'S5MN1' => 'M2',
	'S5MN2' => 'M2',
	'S5NS1' => 'M2',
	'S5NS2' => 'M2',
	'S5NT1' => 'M2',
	'S5PH1' => 'M2',
	'S5PH2' => 'M2',
	'S5PH3' => 'M2',
	'S5YS1' => 'M2',
	'T5D1' => 'M2',
	'T5D2' => 'M2',
	'T5D3' => 'M2',
	'T5DA' => 'M2',
	'DALC' => 'L1',
	'F002' => 'L1',
	'F003' => 'L1',
	'F013' => 'L1',
	'F015' => 'L1',
	'F017' => 'L1',
	'F019' => 'L1',
	'F912' => 'L1',
	'F913' => 'L1',
	'F914' => 'L1',
	'F915' => 'L1',
	'F916' => 'L1',
	'F917' => 'L1',
	'DALM' => 'L1',
	'EALC' => 'L1',
	'EALM' => 'L1',
	'PALC' => 'L1',
	'TPE' => 'L1',
	'F020' => 'L1',
	'F021' => 'L1',
	'F022' => 'L1',
	'F023' => 'L1',
	'F024' => 'L1',
);

while (my ($k, $v) = each(%ce2s)) { if ($$targetdata{'CODEETAPE'} =~ /^$k/) {$$targetdata{'STATUT'} = $v;} }
$$targetdata{categorycode}=substr($$targetdata{'STATUT'},0,1);
$$targetdata{'categorycode'}||="INC";

$$targetdata{'city'}||=" "; 

$$targetdata{'branchcode'}||="U3INC";
#$$targetdata{'cardnumber'}='U3'.$$targetdata{'cardnumber'};

$$targetdata{'surname'}||=$$targetdata{'othernames'}; # NOM_USAGE est vide pour les non maries, voir MT4118
$$targetdata{othernames} = '' if $$targetdata{surname} eq $$targetdata{othernames}; # 3832

#$$targetdata{'dateexpiry'}='2010-11-03';

#$debug && warn "targetdata postprocessed :",@$targetdata{qw(categorycode city)};

---



