NOM: othernames
PRENOM: firstname
NOM_USAGE: surname
ADRESSE_ANNEE: address
ADRESSE_ANNEE2: address2
VILLE_ANNEE: city
CP_ANNEE: zipcode
EMAIL_ANNEE: email
TEL_ANNEE: phone
MOBILE_ANNEE: mobile
EMAIL_PERSO: emailpro
ADRESSE_FIXE: B_address
VILLE_FIXE: B_city
CP_FIXE: B_zipcode
TEL_FIXE: B_phone
DATE_NAISS: dateofbirth
TYPE_STATUT: STATUT
AFF_3_COD: [COMPOSANTE,POLETHEM,branchcode]
LOCAL_AG_COD: LOCAL_AG_COD
CODE_ETAPE: CODEETAPE
NUM_INE: INE
NUM_APPLI_GEST: [APPLIGEST]
IDENT_LDAP: LDAP
--- 
STATUT:
    ADM: PERS
    BIB: PERS
    ENS: EC
    CNRS: EC
branchcode:
    A2: U3BUDAIX
    A301: U3BUDAIX
    A302: U3BUDAIX
    A303: U3BUDAIX
    A305: U3BUDAIX
    A308: U3BUDAIX
    A310: A310
    A311: U3BUDAIX
    A312: U3BUDAIX
    A313: U3BUDAIX
    A314: U3BUDAIX
    A316: U3BUDAIX
    A317: U3BUDAIX
    A319: U3BUDAIX
    A321: U3BUDAIX
    A324: U3BUCAN
    A325: U3BUSSJ
    A326: U3BUDAIX
    A329: U3BUDAIX
    A328: U3BUDAIX
    A399: U3BUDAIX
    D2: U3BUDAIX
    D301: U3BUDAIX
    D302: U3BUDAIX
    D303: U3BUDAIX
    D304: U3BUDAIX
    D305: U3BUDAIX
    D306: U3BUDAIX
    D307: U3BUDAIX
    D308: U3BUDAIX
    D309: U3BUDAIX
    D310: U3BUDAIX
    D311: U3BUDAIX
    D312: U3BUDAIX
    D313: U3BUDAIX
    D314: U3BUDAIX
    D316: U3BUDAIX
    D317: U3BUDAIX
    D318: U3BUDAIX
    D319: U3BUDAIX
    D320: U3BUDAIX
    D321: U3BUDAIX
    D322: U3BUDAIX
    D323: U3BUDAIX
    D325: U3BUDAIX
    D327: U3BUDAIX
    D328: U3BUDAIX
    D330: U3BUDAIX
    D332: U3BUDAIX
    D333: U3BUDAIX
    D335: U3BUDAIX
    D337: U3BUDAIX
    D338: U3BUDAIX
    D339: U3BUDAIX
    D399: U3BUDAIX
    D3E2: U3BUDAIX
    D3SN: U3BUDAIX
    E2: U3BUDAIX
    E301: U3BUDAIX
    E302: U3BUCAN
    E303: U3BUDAIX
    E304: U3BUDAIX
    E305: U3BUDAIX
    E306: U3BUDAIX
    E307: U3BUDAIX
    E308: U3BUDAIX
    E309: U3BUDAIX
    E310: U3BUDAIX
    E311: U3BUDAIX
    E312: U3BUDAIX
    E313: U3BUDAIX
    E315: U3BUDAIX
    E316: U3BUDAIX
    E317: U3BUDAIX
    E320: U3BUDAIX
    E321: U3BUDAIX
    E322: U3BUCAN
    E399: U3BUDAIX
    E3E1: U3BUDAIX
    E3SN: U3BUDAIX
    F2: U3BUIEFEE
    F301: U3BUIEFEE
    F302: U3BUIEFEE
    F303: U3BUIEFEE
    F306: U3BUIEFEE
    F307: U3BUIEFEE
    F309: U3BUIEFEE
    F310: U3BUIEFEE
    F3E1: U3BUIEFEE
    G2: U3BUIEFEE
    G301: U3BUIEFEE
    G302: U3BUIEFEE
    G303: U3BUIEFEE
    G304: U3BUIEFEE
    G306: U3BUIEFEE
    G307: U3BUIEFEE
    G3E1: U3BUIEFEE
    N2: U3BUSSJ
    N301: U3BUSSJ
    N302: U3BUSSJ
    N303: U3BUSSJ
    N304: U3BUSSJ
    N306: U3BUSSJ
    N307: U3BUSSJ
    N308: U3BUSSJ
    N309: U3BUSSJ
    N310: U3BUSSJ
    N311: U3BUSSJ
    N315: U3BUSSJ
    N320: U3BUSSJ
    N321: U3BUSSJ
    N322: U3BUSSJ
    N323: U3BUSSJ
    N324: U3BUSSJ
    N325: U3BUSSJ
    N326: U3BUSSJ
    N399: U3BUSSJ
    N3E1: U3BUSSJ
    N3E2: U3BUSSJ
    N3E3: U3BUSSJ
    N3E4: U3BUSSJ
    N3E5: U3BUSSJ
    N3E6: U3BUSSJ
    N3E7: U3BUSSJ
    N3E8: U3BUSSJ
    R2: U3BUDAIX
    R3E1: U3BUDAIX
    S2: U3BUSSJ
    S301: U3BUMTP
    S301: U3BUSSJ
    S302: U3BUMTP
    S302: U3BUSSJ
    S303: U3BUSSJ
    S304: U3BUSSJ
    S305: U3BUSSJ
    S306: U3BUMTP
    S306: U3BUSSJ
    S307: U3BUSSJ
    S308: U3BUSSJ
    S309: U3BUSSJ
    S310: U3BUSSJ
    S311: U3BUSSJ
    S312: U3BUSSJ
    S313: U3BUSSJ
    S314: U3BUSSJ
    S315: U3BUSSJ
    S316: U3BUSSJ
    S317: U3BUSSJ
    S318: U3BUSSJ
    S319: U3BUSSJ
    S320: U3BUSSJ
    S399: U3BUSSJ
    S3E1: U3BUSSJ
    S3E2: U3BUSSJ
    S3E3: U3BUSSJ
    S3E4: U3BUSSJ
    S3SN: U3BUSSJ
    T2: U3BUIAE
    T301: U3BUIAE
    T302: U3BUIAE
    T303: U3BUIAE
    T305: U3BUIAE
    T306: U3BUIAE
    T307: U3BUIAE
    T308: U3BUIAE
    T309: U3BUIAE
    T310: U3BUIAE
    T3E1: U3BUIAE
    UPCAM: U3BUDAIX
    V301: U3BUSSJ
    V306: U3BUSSJ
    V307: U3BUSSJ
    V309: U3BUSSJ
    V399: U3BUSSJ
    V3SN: U3BUSSJ
    V3E1: U3BUSSJ
    X301: U3BUDAIX
    X302: U3BUDAIX
    X303: U3BUDAIX
    X304: U3BUDAIX
    X305: U3BUDAIX
    X306: U3BUDAIX
    X307: U3BUDAIX
    X308: U3BUDAIX
    X309: U3BUDAIX
    X310: U3BUDAIX
    X311: U3BUDAIX
    X313: U3BUDAIX
    X314: U3BUDAIX
    X315: U3BUDAIX
    X316: U3BUDAIX
    X318: U3BUDAIX
    X319: U3BUDAIX
    X320: U3BUDAIX
    X323: U3BUDAIX
    X324: U3BUDAIX
    X328: U3BUDAIX
    X329: U3BUDAIX
    X399: U3BUDAIX
    Y2: U3BUDAIX
    Y302: U3BUDAIX
    Y307: U3BUIAE
    Y399: U3BUDAIX
    Z2: U3BUSSJ
    Z301: U3BUSSJ
    Z302: U3BUSSJ
    Z306: U3BUSSJ
    Z307: U3BUSSJ
    Z308: U3BUSSJ
    Z309: U3BUSSJ
    Z311: U3BUSSJ
    Z312: U3BUSSJ
    Z313: U3BUSSJ
    Z315: U3BUSSJ
    Z317: U3BUSSJ
    Z321: U3BUSSJ
    Z322: U3BUSSJ
    Z323: U3BUSSJ
    Z324: U3BUSSJ
    Z325: U3BUSSJ
    Z326: U3BUSSJ
    Z328: U3BUSSJ
    Z329: U3BUSSJ
    Z399: U3BUSSJ
POLETHEM:
    A2: Droit
    A301: Droit
    A302: Droit
    A303: Droit
    A304: Droit
    A305: Droit
    A307: Droit
    A308: Droit
    A309: Sciences
    A310: A310
    A311: Droit
    A312: Droit
    A313: Droit
    A314: Droit
    A316: Droit
    A317: Droit
    A319: Droit
    A321: Droit
    A322: Droit
    A323: Droit
    A324: Droit
    A325: Sciences
    A326: Droit
    A328: Droit
    A399: Droit
    D2: Droit
    D301: Droit
    D302: Droit
    D303: Droit
    D304: Droit
    D305: Droit
    D306: Droit
    D307: Droit
    D308: Droit
    D309: Droit
    D310: Droit
    D311: Droit
    D312: Droit
    D313: Droit
    D314: Droit
    D316: Droit
    D317: Droit
    D318: Droit
    D319: Droit
    D320: Droit
    D321: Droit
    D322: Droit
    D323: Droit
    D325: Droit
    D327: Droit
    D328: Droit
    D330: Droit
    D332: Droit
    D333: Droit
    D335: Droit
    D337: Droit
    D338: Droit
    D339: Droit
    D399: Droit
    D3E1: Droit
    D3E2: Droit
    D3SN: Droit
    E2: Economie
    E301: Economie
    E302: Economie
    E303: Economie
    E304: Economie
    E305: Economie
    E306: Economie
    E307: Economie
    E308: Economie
    E309: Economie
    E310: Economie
    E311: Economie
    E312: Economie
    E313: Economie
    E315: Economie
    E316: Economie
    E317: Economie
    E318: Economie
    E319: Economie
    E320: Economie
    E321: Economie
    E322: Economie
    E399: Economie
    E3E1: Economie
    E3SN: Economie
    F2: Lettres
    F301: Lettres
    F302: Lettres
    F303: Lettres
    F306: Lettres
    F307: Lettres
    F309: Lettres
    F310: Lettres
    F3E1: Lettres
    G2: Droit
    G301: Droit
    G302: Droit
    G303: Droit
    G304: Droit
    G306: Droit
    G307: Droit
    G3E1: Droit
    N2: Sciences
    N301: Sciences
    N302: Sciences
    N303: Sciences
    N304: Sciences
    N306: Sciences
    N307: Sciences
    N308: Sciences
    N309: Sciences
    N310: Sciences
    N311: Sciences
    N315: Sciences
    N320: Sciences
    N321: Sciences
    N322: Sciences
    N323: Sciences
    N324: Sciences
    N325: Sciences
    N326: Sciences
    N399: Sciences
    N3E1: Sciences
    N3E2: Sciences
    N3E3: Sciences
    N3E4: Sciences
    N3E5: Sciences
    N3E6: Sciences
    N3E7: Sciences
    N3E8: Sciences
    R2: Droit
    R3E1: Droit
    S2: Sciences
    S301: Sciences
    S302: Sciences
    S303: Sciences
    S304: Sciences
    S305: Sciences
    S306: Sciences
    S307: Sciences
    S308: Sciences
    S309: Sciences
    S310: Sciences
    S311: Sciences
    S312: Sciences
    S313: Sciences
    S314: Sciences
    S315: Sciences
    S316: Sciences
    S317: Sciences
    S318: Sciences
    S319: Sciences
    S320: Sciences
    S399: Sciences
    S3E1: Sciences
    S3E2: Sciences
    S3E3: Sciences
    S3E4: Sciences
    S3SN: Sciences
    T2: Economie
    T301: Economie
    T302: Economie
    T303: Economie
    T305: Economie
    T306: Economie
    T307: Economie
    T308: Economie
    T309: Economie
    T310: Economie
    T3E1: Economie
    UPCAM: Droit
    V301: Sciences
    V306: Sciences
    V307: Sciences
    V309: Sciences
    V399: Sciences
    V3E1: Sciences
    V3SN: Sciences
    X301: Droit
    X302: Droit
    X303: Droit
    X304: Droit
    X305: Droit
    X306: Droit
    X307: Droit
    X308: Droit
    X309: Droit
    X310: Droit
    X311: Droit
    X313: Droit
    X314: Droit
    X315: Droit
    X316: Droit
    X318: Droit
    X319: Droit
    X320: Droit
    X323: Droit
    X324: Droit
    X328: Droit
    X329: Droit
    X399: Droit
    Y2: Economie
    Y302: Economie
    Y303: Economie
    Y307: Economie
    Y399: Economie
    Z2: Sciences
    Z301: Sciences
    Z302: Sciences
    Z306: Sciences
    Z307: Sciences
    Z308: Sciences
    Z309: Sciences
    Z311: Sciences
    Z312: Sciences
    Z313: Sciences
    Z315: Sciences
    Z317: Sciences
    Z321: Sciences
    Z322: Sciences
    Z323: Sciences
    Z324: Sciences
    Z325: Sciences
    Z326: Sciences
    Z328: Sciences
    Z329: Sciences
    Z399: Sciences
COMPOSANTE:
    A2: U3SERVCENT
    A301: U3SERVCENT
    A302: U3SERVCENT
    A303: U3SERVCENT
    A304: U3SERVCENT
    A305: U3SERVCENT
    A307: U3SERVCENT
    A308: U3SERVCENT
    A309: U3SERVCENT
    A310: U3SERVCENT
    A311: U3SERVCENT
    A312: U3SERVCENT
    A313: U3SERVCENT
    A314: U3SERVCENT
    A316: U3SERVCENT
    A317: U3SERVCENT
    A319: U3SERVCENT
    A321: U3SERVCENT
    A322: U3SERVCENT
    A323: U3SERVCENT
    A324: U3FDSPMRS
    A325: U3SERVCENT
    A326: U3SERVCENT
    A328: U3SERVCENT
    A399: U3SERVCENT
    D2: U3FDSPAIX
    D301: U3FDSPAIX
    D302: U3FDSPAIX
    D302: U3FDSPMRS
    D303: U3FDSPAIX
    D304: U3FDSPAIX
    D305: U3FDSPAIX
    D306: U3FDSPAIX
    D307: U3FDSPAIX
    D308: U3FDSPAIX
    D309: U3FDSPAIX
    D310: U3FDSPAIX
    D311: U3FDSPAIX
    D312: U3FDSPAIX
    D313: U3FDSPAIX
    D314: U3FDSPAIX
    D316: U3FDSPAIX
    D317: U3FDSPAIX
    D318: U3FDSPAIX
    D319: U3FDSPAIX
    D320: U3FDSPAIX
    D321: U3FDSPAIX
    D322: U3FDSPAIX
    D323: U3FDSPAIX
    D325: U3FDSPAIX
    D327: U3FDSPAIX
    D328: U3FDSPAIX
    D330: U3FDSPAIX
    D332: U3FDSPAIX
    D333: U3FDSPAIX
    D335: U3FDSPAIX
    D337: U3FDSPAIX
    D338: U3FDSPAIX
    D339: U3FDSPAIX
    D399: U3FDSPAIX
    D3E1: U3FDSPAIX
    D3E1: U3FDSPMRS
    D3E2: U3IAR
    D3SN: U3FDSPAIX
    E2: U3FEAAIX
    E301: U3FEAAIX
    E302: U3FEAAIX
    E302: U3FEAMRS
    E303: U3FEAAIX
    E304: U3FEAAIX
    E305: U3FEAAIX
    E306: U3FEAAIX
    E306: U3FEAFORB
    E307: U3FEAAIX
    E308: U3FEAAIX
    E309: U3FEAAIX
    E310: U3FEAAIX
    E311: U3FEAAIX
    E312: U3FEAFORB
    E313: U3FEAAIX
    E315: U3FEAFORB
    E316: U3FEAFORB
    E317: U3FEAFORB
    E318: U3FEAFORB
    E319: U3FEAAIX
    E320: U3FEAAIX
    E321: U3FEAAIX
    E322: U3FEAMRS
    E399: U3FEAAIX
    E3E1: U3FEAAIX
    E3SN: U3FEAAIX
    F2: U3IEFEE
    F301: U3IEFEE
    F302: U3IEFEE
    F303: U3IEFEE
    F306: U3IEFEE
    F307: U3IEFEE
    F309: U3IEFEE
    F310: U3IEFEE
    F3E1: U3IEFEE
    G2: U3IMPGTAIX
    G301: U3IMPGTAIX
    G302: U3IMPGTAIX
    G303: U3IMPGTAIX
    G304: U3IMPGTAIX
    G306: U3IMPGTAIX
    G307: U3IMPGTAIX
    G3E1: U3IMPGTAIX
    N2: U3IUTMRS
    N301: U3IUTMRS
    N302: U3IUTMRS
    N303: U3IUTMRS
    N304: U3IUTMRS
    N306: U3IUTMRS
    N307: U3IUTMRS
    N308: U3IUTMRS
    N309: U3IUTMRS
    N310: U3IUTMRS
    N311: U3IUTMRS
    N315: U3IUTMRS
    N315: U3IUTSAL
    N320: U3IUTMRS
    N321: U3IUTMRS
    N322: U3IUTMRS
    N323: U3IUTMRS
    N324: U3IUTMRS
    N325: U3IUTMRS
    N326: U3IUTMRS
    N399: U3IUTMRS
    N3E1: U3IUTMRS
    N3E2: U3IUTMRS
    N3E3: U3IUTMRS
    N3E4: U3IUTMRS
    N3E5: U3IUTMRS
    N3E6: U3IUTMRS
    N3E7: U3IUTMRS
    N3E8: U3IUTMRS
    N3E8: U3IUTSAL
    R2: U3IAR
    R3E1: U3IAR
    S2: U3FSTMRS
    S301: U3FSTAIX
    S301: U3FSTMRS
    S302: U3FSTAIX
    S302: U3FSTMRS
    S303: U3FSTMRS
    S304: U3FSTMRS
    S305: U3FSTMRS
    S306: U3FSTAIX
    S306: U3FSTMRS
    S307: U3FSTMRS
    S308: U3FSTMRS
    S309: U3FSTMRS
    S310: U3FSTMRS
    S311: U3FSTMRS
    S312: U3FSTMRS
    S313: U3FSTMRS
    S314: U3FSTMRS
    S315: U3FSTMRS
    S316: U3FSTMRS
    S317: U3FSTMRS
    S318: U3FSTMRS
    S319: U3FSTMRS
    S320: U3FSTMRS
    S399: U3FSTMRS
    S3E1: U3FSTMRS
    S3E2: U3FSTMRS
    S3E3: U3FSTMRS
    S3E4: U3FSTMRS
    S3SN: U3FSTMRS
    T2: U3IAE
    T301: U3IAE
    T302: U3IAE
    T303: U3IAE
    T305: U3IAE
    T306: U3IAE
    T307: U3IAE
    T308: U3IAE
    T309: U3IAE
    T310: U3IAE
    T3E1: U3IAE
    UPCAM: U3SERVCENT
    V301: U3FSTMRS
    V306: U3FSTMRS
    V307: U3FSTMRS
    V309: U3FSTMRS
    V3E1: U3FSTMRS
    V399: U3FSTMRS
    V3SN: U3FSTMRS
    X301: U3FDSPAIX
    X302: U3FDSPAIX
    X303: U3FDSPAIX
    X304: U3FDSPAIX
    X305: U3FDSPAIX
    X306: U3FDSPAIX
    X307: U3FDSPAIX
    X308: U3FDSPAIX
    X309: U3FDSPAIX
    X310: U3FDSPAIX
    X311: U3FDSPAIX
    X313: U3FDSPAIX
    X314: U3FDSPAIX
    X315: U3FDSPAIX
    X316: U3FDSPAIX
    X318: U3FDSPAIX
    X319: U3FDSPAIX
    X320: U3FDSPAIX
    X323: U3FDSPAIX
    X324: U3FDSPAIX
    X328: U3FDSPAIX
    X329: U3FDSPAIX
    X399: U3FDSPAIX
    Y2: U3FEAAIX
    Y302: U3FEAAIX
    Y303: U3FEAAIX
    Y307: U3IAE
    Y399: U3FEAAIX
    Z2: U3FSTMRS
    Z301: U3FSTMRS
    Z302: U3FSTMRS
    Z306: U3FSTMRS
    Z307: U3FSTMRS
    Z308: U3FSTMRS
    Z309: U3FSTMRS
    Z311: U3FSTMRS
    Z312: U3FSTMRS
    Z313: U3FSTMRS
    Z315: U3FSTMRS
    Z317: U3FSTMRS
    Z321: U3FSTMRS
    Z322: U3FSTMRS
    Z323: U3FSTMRS
    Z324: U3FSTMRS
    Z325: U3FSTMRS
    Z326: U3FSTMRS
    Z328: U3FSTMRS
    Z329: U3FSTMRS
    Z399: U3FSTMRS
--- 
  - firstname,surname,dateofbirth
--- 
--- |
$$targetdata{'city'}||=" "; 
#$debug && warn "targetdata postprocessed :",@$targetdata{qw(categorycode city)}; 
$$targetdata{'ETABLISSEM'}='U3';

# cas spéciaux branchcode
if ( $$targetdata{'branchcode'} eq 'A304' ) {
    $$targetdata{'branchcode'} = $$targetdata{'LOCAL_AG_COD'} eq '310' ? 'U3BUSSJ' : 'U3BUDAIX';
} elsif ( $$targetdata{'branchcode'} eq 'A307' ) {
    if ( $$targetdata{'LOCAL_AG_COD'} eq '310' ) {
        $$targetdata{'branchcode'} = 'U3BUSSJ';
    } elsif ( $$targetdata{'LOCAL_AG_COD'} eq '347' ) {
        $$targetdata{'branchcode'} = 'U3BUCAN';
    } else {
        $$targetdata{'branchcode'} = 'U3BUDAIX';
    }
} elsif ( $$targetdata{'branchcode'} eq 'A309' ) {
    $$targetdata{'branchcode'} = $$targetdata{'LOCAL_AG_COD'} eq '294' ? 'U3BUDAIX' : 'U3BUSSJ';
} elsif ( $$targetdata{'branchcode'} eq 'D302' ) {
    $$targetdata{'branchcode'} = $$targetdata{'LOCAL_AG_COD'} eq '347' ? 'U3BUCAN' : 'U3BUDAIX';
} elsif ( $$targetdata{'branchcode'} eq 'D3E1' ) {
    $$targetdata{'branchcode'} = $$targetdata{'LOCAL_AG_COD'} eq '347' ? 'U3BUCAN' : 'U3BUDAIX';
} elsif ( $$targetdata{'branchcode'} eq 'E302' ) {
    $$targetdata{'branchcode'} = $$targetdata{'LOCAL_AG_COD'} eq '347' ? 'U3BUCAN' : 'U3BUDAIX';
} elsif ( $$targetdata{'branchcode'} eq 'A310' ) {
    my %hash = (
        '294' => 'U3BUDAIX',
        '299' => 'U3BUIEFEE',
        '301' => 'U3BUMTP',
        '310' => 'U3BUSSJ',
        '322' => 'U3BUIAE',
        '347' => 'U3BUCAN',
    );
    $$targetdata{'branchcode'} = $hash{$$targetdata{'LOCAL_AG_COD'}} || 'U3BUDAIX';
} elsif ( $$targetdata{'branchcode'} eq 'A322' or $$targetdata{'branchcode'} eq 'A323' ) {
    $$targetdata{'branchcode'} = $$targetdata{'LOCAL_AG_COD'} eq '310' ? 'U3BUSSJ' : 'U3BUDAIX';
}

# cas spéciaux polethem
if ($$targetdata{'AFF_3_COD'} eq 'A304' or
    $$targetdata{'AFF_3_COD'} eq 'A307' or
    $$targetdata{'AFF_3_COD'} eq 'A322' or
    $$targetdata{'AFF_3_COD'} eq 'A323' ) {
    if ( $$targetdata{'LOCAL_AG_COD'} eq '310' ) {
        $$targetdata{'POLETHEM'} = 'Sciences';
    }
} elsif ( $$targetdata{'AFF_3_COD'} eq 'A309' ) {
    if ( $$targetdata{'LOCAL_AG_COD'} eq '294' ) {
        $$targetdata{'POLETHEM'} = 'Droit';
    }
} elsif ( $$targetdata{'AFF_3_COD'} eq 'A310' ) {
    my %hash = (
        '294' => 'Droit',
        '299' => 'Lettres',
        '301' => 'Sciences',
        '310' => 'Sciences',
        '322' => 'Economie',
        '347' => 'Droit',
    );  
    $$targetdata{'POLETHEM'} = $hash{$$targetdata{'LOCAL_AG_COD'}};
}

$$targetdata{'branchcode'} ||= "U3INC";
$$targetdata{'categorycode'} = "P";
#$$targetdata{'cardnumber'} = 'U3'.$$targetdata{'cardnumber'};

$$targetdata{othernames} = '' if $$targetdata{surname} eq $$targetdata{othernames}; # 3832
---
















