<div id="subtypes" class="container">
    <fieldset>
        <legend>Subtype limits</legend>                 
        <select name="filters" class="subtype">
            <option value="" selected="selected" class="menuheader">Any Audience</option>
            <option value="aud:a">Easy</option>
            <option value="aud:c">Juvenile</option>
            <option value="aud:d">Young Adult</option>
            <option value="aud:e">Adult</option>
        </select>
        <select name="filters" class="subtype">
            <option value="" selected="selected" class="menuheader">Any Content</option>
            <option value="fic:1">Fiction</option>
            <option value="fic:0">Non Fiction</option>
            <option value="bio:b">Biography</option>
            <option value="mus:j">Musical recording</option>
            <option value="mus:i">Non-musical recording</option>
        </select>
        <select name="filters" class="subtype">
            <option value="" selected="selected" class="menuheader">Any Format</option>
            <option value="l-format:ta">Regular print</option>
            <option value="l-format:tb">Large print</option>
            <option value="l-format:fk">Braille</option>
            <option value="">-----------</option>
            <option value="l-format:sd">CD audio</option>
            <option value="l-format:ss">Cassette recording</option>
            <option value="l-format:vf">VHS tape / Videocassette</option>
            <option value="l-format:vd">DVD video / Videodisc</option>
            <option value="l-format:co">CD Software</option>
            <option value="l-format:cr">Website</option>
        </select>
        <select name="filters" class="subtype">
            <option value="">Additional Content Types for Books/Printed Materials</option>
            <option value="ctype:a">Abstracts/summaries</option>
            <option value="ctype:b">Bibliographies</option>
            <option value="ctype:c">Catalogs</option>
            <option value="ctype:d">Dictionaries</option>
            <option value="ctype:e">Encyclopedias </option>
            <option value="ctype:f">Handbooks</option>
            <option value="ctype:g">Legal articles</option>
            <option value="ctype:i">Indexes</option>
            <option value="ctype:j">Patent document</option>
            <option value="ctype:k">Discographies</option>
            <option value="ctype:l">Legislation</option>
            <option value="ctype:m">Theses</option>
            <option value="ctype:n">Surveys</option>
            <option value="ctype:o">Reviews</option>
            <option value="ctype:p">Programmed texts</option>
            <option value="ctype:q">Filmographies</option>
            <option value="ctype:r">Directories</option>
            <option value="ctype:s">Statistics</option>
            <option value="ctype:t">Technical reports</option>
            <option value="ctype:v">Legal cases and case notes</option>
            <option value="ctype:w">Law reports and digests</option>
            <option value="ctype:z">Treaties </option>
        </select>
    </fieldset>
</div>

